#!/bin/sh

# Script to make alternative setup
su -c "apt update -y && apt upgrade -y; apt install -y xorg libx11-dev libxft-dev libxinerama-dev clang git make wget curl sxhkd doas pulseaudio alsa-utils dunst
echo \"
permit nopass $(whoami)
permit nopass $(whoami) cmd /usr/bin/tee args /sys/class/backlight/*/brightness
\" > /etc/doas.conf"
# doas ^

# disable root password
doas -- sed -i 's/root:x:0:0:root:\/root:\/bin\/bash/root:x:0:0:root:\/root:\/sbin\/nologin/g' /etc/passwd

# suckless
# TODO: 1) make and apply own patches 2) keep modified builds in my repo
git clone https://git.suckless.org/dwm
git clone https://git.suckless.org/st
git clone https://git.suckless.org/dmenu

cd dwm;   doas -- make clean install; cd ..
cd st;    doas -- make clean install; cd ..
cd dmenu; doas -- make clean install; cd ..

# google-chrome
wget --show-progress "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
export PATH="$PATH:/usr/sbin"
doas -- apt-get -f install
doas -- dpkg -i google-chrome-stable_current_amd64.deb
rm -f https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# keyboard default option
doas -- sed -i 's/XKBOPTIONS=""/XKBOPTIONS="caps:swapescape"/g' /etc/default/keyboard

# set doas back to permit for user
doas -- sed -i "0,/nopass/permit" /etc/doas.conf


# sxhkd
mkdir -p .config/sxhkd
echo "
# sound: superuser.com/questions/1577281/xev-not-detecting-media-keys
# NOTE: shift is temporary
shift + XF86AudioMute
	amixer set 'Master' toggle
	notify-send \"\$(amixer set 'Master' toggle | grep -o --color=none '\[on\]\|\[off\]')\"
shift + XF86AudioRaiseVolume
	notify-send \"\$(amixer set 'Master' \\\"\$sound_step\\\"+ | grep -oE --color=none '[0-9]{1,3}%')\"
shift + XF86AudioLowerVolume
	notify-send \"\$(amixer set 'Master' \\\"\$sound_step\\\"- | grep -oE --color=none '[0-9]{1,3}%')\"

#alt + shift
#	cur_map=\$(setxkbmap -query | grep --color=no -oE \"us\|ee\");if [[ "\$cur_map" = us ]]; then new_map=ee; else new_map=us; fi; setxkbmap -option caps:swapescape \$new_map

# brightness_step
shift + XF86MonBrightnessUp
	cat \$((\$(cat /sys/class/backlight/*/brightness)+\$brightness_step)) | doas tee /sys/class/backlight/*/brightness
shift + XF86MonBrightnessDown
	cat \$((\$(cat /sys/class/backlight/*/brightness)-\$brightness_step)) | doas tee /sys/class/backlight/*/brightness
" > .config/sxhkd/sxhkdrc

# .xinitrc
echo "setxkbmap -option caps:swapescape
export max_brightness=$(cat /sys/class/backlight/*/max_brightness)
export brightness_step=$(echo $(($max_brightness/20)))
export sound_step="5%"
export LESS=\"-R\"
while xsetroot -name \"\`setxkbmap -query | grep --color=none -oE \\\"us\\\|ee\\\"\` | \`cat /sys/class/power_supply/BAT0/capacity\` | \`date \\\"+%a %F %R\\\"\`\"
do 
	sleep 60
done &
amixer set 'Master' on
amixer set 'Master' 30%
sxhkd &
pulseaudio --start &
dunst & # notification receiver
exec dwm" > .xinitrc
does -- systemctl reboot

