#!/bin/sh

set -e

# Script to make alternative setup
su -c "apt update -y && apt upgrade -y; apt install -y xorg libx11-dev libxft-dev libxinerama-dev clang git make wget curl sxhkd doas pulseaudio alsa-utils
echo \"permit nopass $(whoami)
permit nopass $(whoami) cmd /usr/bin/tee args /sys/class/backlight/*/brightness\" > /etc/doas.conf"
# doas ^

# disable root password
doas -- sed -i 's/root:x:0:0:root:\/root:\/bin\/bash/root:x:0:0:root:\/root:\/sbin\/nologin/g'

# suckless
# TODO: 1) make and apply own patches 2) keep modified builds in my repo
git clone https://git.suckless.org/dwm
git clone https://git.suckless.org/st
git clone https://git.suckless.org/dmenu

cd dwm;   doas -- make clean install; cd ..
cd st;    doas -- make clean install; cd ..
cd dmenu; doas -- make clean install; cd ..

# google-chrome
wget --show-progress "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
export PATH="$PATH:/usr/sbin"
doas -- apt-get -f install
doas -- dpkg -i google-chrome-stable_current_amd64.deb

# keyboard default option
doas -- sed -i 's/XKBOPTIONS=""/XKBOPTIONS="caps:swapescape"/g' /etc/default/keyboard

# set doas back to permit for user
doas -- sed -i "0,/nopass/permit" /etc/doas.conf

# sxhkd
mkdir -p .config/sxhkd
echo "
# sound: superuser.com/questions/1577281/xev-not-detecting-media-keys
# NOTE: shift is temporary
shift + XF86AudioMute
	amixer set 'Master' toggle
shift + XF86AudioRaiseVolume
	amixer set 'Master' \"\$sound_step\"+
shift + XF86AudioLowerVolume
	amixer set 'Master' \"\$sound_step\"-

#alt + shift
#	cur_map=\$(setxkbmap -query | grep --color=no layout | sed 's/\ \|\t\|layout://g');if [[ "\$cur_map" = us ]]; then new_map=ee; else new_map=us; fi; setxkbmap -option caps:swapescape \$new_map

# brightness_step
shift + XF86MonBrightnessUp
	cat \$((\$(cat /sys/class/backlight/*/brightness)+\$brightness_step)) | doas tee /sys/class/backlight/*/brightness
shift + XF86MonBrightnessDown
	cat \$((\$(cat /sys/class/backlight/*/brightness)-\$brightness_step)) | doas tee /sys/class/backlight/*/brightness
" > .config/sxhkd/sxhkdrc

# .xinitrc
echo "setxkbmap -option caps:swapescape
export brightness_step=$(echo $(($(cat /sys/lass/backlight/*/max_brightness)/20)))
export sound_step="5%"
while xsetroot -name \"\`date \\\"+%a %F %R\\\"\`|`cat /sys/class/power_supply/BAT0/capacity`\"
do 
	sleep 60
done &
amixer set 'Master' on
amixer set 'Master' 30%
sxhkd &
# pulseaudio --start &
exec dwm" > .xinitrc
systemctl reboot
