#!/bin/sh

# Script to set up my debian environment.

set -xe

user=$(who)
user=${user%% *}

# packages
gui="gnome-core"
privilege="doas"
developer="git wget curl vim-gtk exuberant-ctags golang"
# vim-gtk allows to copy to system clipboard
# exuberant-ctags for vim autocomplete
utility="htop xclip zip unzip"
entertainment="vlc transmission"
markup="texlive-full pandoc zathura zathura-pdf-poppler"
packages_list="$gui $privilege $developer $utility $entertainment" # $markup

printf "Get the post-setup script and set it to autostart\n"
wget raw.githubusercontent.com/moledoc/molenew/main/post-setup
chmod +x post-setup

printf "Update && upgrade system\nSetup doas\nInstall packages\nReboot\n"
su -c "apt update -y && apt upgrade -y; \ 
printf \"permit nopass ${user}\n\" > /usr/local/etc/doas.conf; \
printf \"permit nopass ${user}\n\" > /etc/doas.conf; \
apt install --dry-run $packages_list; \
apt install -y $packages_list; \
systemctl reboot" 
